# Generated by Django 4.2.3 on 2023-07-16 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PE', 'Pendiente'), ('PR', 'Procesando'), ('SH', 'Enviado'), ('DE', 'Entregado'), ('CA', 'Cancelado')], default='PE', max_length=2, verbose_name='Estado')),
                ('shipment_method', models.CharField(choices=[('P', 'Retirar en tienda'), ('S', 'Estándar'), ('E', 'Express')], default='P', max_length=1, verbose_name='Método de envío')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
